In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import string

In [ ]:
train=pd.read_csv('Train_Data.csv')

In [ ]:
train

                                                headline  is_sarcastic
0      supreme court votes 7-2 to legalize all worldl...             1
1      hungover man horrified to learn he made dozens...             1
2      emily's list founder: women are the 'problem s...             0
3          send your kids back to school with confidence             0
4              watch: experts talk pesticides and health             0
...                                                  ...           ...
44257   greece seeks to reassure europe as tensions rise             0
44258  vatican says transgender man cannot become a g...             0
44259  protesters ejected from donald trump rally aft...             0
44260        italian recipes that are oldies but goodies             0
44261  area loser blissfully unaffected by whims of s...             1

[44262 rows x 2 columns]

In [ ]:
train.isnull().sum()

headline        0
is_sarcastic    0
dtype: int64

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44262 entries, 0 to 44261
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   headline      44262 non-null  object
 1   is_sarcastic  44262 non-null  int64
dtypes: int64(1), object(1)
memory usage: 691.7+ KB

In [ ]:
train['is_sarcastic'].value_counts()

0    23958
1    20304
Name: is_sarcastic, dtype: int64

In [ ]:
X=train.drop(['is_sarcastic'], axis=1)
X

                                                headline
0      supreme court votes 7-2 to legalize all worldl...
1      hungover man horrified to learn he made dozens...
2      emily's list founder: women are the 'problem s...
3          send your kids back to school with confidence
4              watch: experts talk pesticides and health
...                                                  ...
44257   greece seeks to reassure europe as tensions rise
44258  vatican says transgender man cannot become a g...
44259  protesters ejected from donald trump rally aft...
44260        italian recipes that are oldies but goodies
44261  area loser blissfully unaffected by whims of s...

[44262 rows x 1 columns]

In [ ]:
y=train['is_sarcastic']
y

0        1
1        1
2        0
3        0
4        0
        ..
44257    0
44258    0
44259    0
44260    0
44261    1
Name: is_sarcastic, Length: 44262, dtype: int64

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=42)

In [ ]:
import string
X_train['char_count'] = X_train['headline'].apply(len)
X_train['word_count'] = X_train['headline'].apply(lambda x: len(x.split()))
X_train['punctuation_count'] = X_train['headline'].apply(lambda x: len("".join(_ for _ in x if _ in string.punctuation))) 
X_train['title_word_count'] = X_train['headline'].apply(lambda x: len([wrd for wrd in x.split() if wrd.istitle()]))
X_train['upper_case_word_count'] = X_train['headline'].apply(lambda x: len([wrd for wrd in x.split() if wrd.isupper()]))


X_test['char_count'] = X_test['headline'].apply(len)
X_test['word_count'] = X_test['headline'].apply(lambda x: len(x.split()))
X_test['punctuation_count'] = X_test['headline'].apply(lambda x: len("".join(_ for _ in x if _ in string.punctuation))) 
X_test['title_word_count'] = X_test['headline'].apply(lambda x: len([wrd for wrd in x.split() if wrd.istitle()]))
X_test['upper_case_word_count'] = X_test['headline'].apply(lambda x: len([wrd for wrd in x.split() if wrd.isupper()]))

In [ ]:
X_train.head(5)

,headline,char_count,word_count,punctuation_count,title_word_count,upper_case_word_count
34059,authoritarian secretary of transportation decl...,106,15,0,0,0
6098,study: marriages between perfectly matched cou...,88,13,1,0,0
6252,employee wellness programs aren't so voluntary...,54,7,1,0,0
20826,p is for p*ssy' is the alphabet book of your w...,55,12,2,0,0
24719,nothing going right for area surgeon today,42,7,0,0,0

In [ ]:
X_test.head()

,headline,char_count,word_count,punctuation_count,title_word_count,upper_case_word_count
12782,north dakota not heard from in 48 hours,39,8,0,0,0
42915,report: it going to take way more than an inco...,106,19,1,0,0
33043,states' rights rancher ryan bundy to run for n...,60,10,1,0,0
1121,watching thousands march in his honor unlocks ...,85,13,2,0,0
38782,"during the debate, these two did the unthinkab...",71,12,1,0,0

In [ ]:


lr = LogisticRegression(C=1, random_state=42, solver='liblinear')

In [ ]:
lr.fit(X_train.drop(['headline'], axis=1), y_train)
predictions1 = lr.predict(X_test.drop(['headline'], axis=1))

print(classification_report(y_test, predictions1))
pd.DataFrame(confusion_matrix(y_test, predictions1))

              precision    recall  f1-score   support

           0       0.61      0.72      0.66      5947
           1       0.59      0.47      0.53      5119

    accuracy                           0.61     11066
   macro avg       0.60      0.60      0.60     11066
weighted avg       0.61      0.61      0.60     11066

      0     1
0  4300  1647
1  2700  2419

In [ ]:
knn=KNeighborsClassifier(n_neighbors=6)
knn.fit(X_train.drop(['headline'], axis=1), y_train)
predictions2 = knn.predict(X_test.drop(['headline'], axis=1))
print(classification_report(y_test, predictions2))
pd.DataFrame(confusion_matrix(y_test, predictions2))

              precision    recall  f1-score   support

           0       0.61      0.76      0.68      5947
           1       0.61      0.44      0.51      5119

    accuracy                           0.61     11066
   macro avg       0.61      0.60      0.60     11066
weighted avg       0.61      0.61      0.60     11066

      0     1
0  4519  1428
1  2856  2263

In [ ]:
dt=DecisionTreeClassifier()
dt.fit(X_train.drop(['headline'], axis=1), y_train)
predictions3 = dt.predict(X_test.drop(['headline'], axis=1))
print(classification_report(y_test, predictions3))
pd.DataFrame(confusion_matrix(y_test, predictions3))

              precision    recall  f1-score   support

           0       0.64      0.75      0.69      5947
           1       0.64      0.51      0.57      5119

    accuracy                           0.64     11066
   macro avg       0.64      0.63      0.63     11066
weighted avg       0.64      0.64      0.63     11066

      0     1
0  4442  1505
1  2488  2631

In [ ]:
rfs=RandomForestClassifier()
rfs.fit(X_train.drop(['headline'], axis=1), y_train)
predictions4 = rfs.predict(X_test.drop(['headline'], axis=1))
print(classification_report(y_test, predictions4))
pd.DataFrame(confusion_matrix(y_test, predictions4))

              precision    recall  f1-score   support

           0       0.65      0.72      0.68      5947
           1       0.63      0.54      0.58      5119

    accuracy                           0.64     11066
   macro avg       0.64      0.63      0.63     11066
weighted avg       0.64      0.64      0.64     11066

      0     1
0  4291  1656
1  2341  2778

In [ ]:
test=pd.read_csv('Test_Data.csv')

In [ ]:
test

                                                headline
0      area stand-up comedian questions the deal with...
1      dozens of glowing exit signs mercilessly taunt...
2      perfect response to heckler somewhere in prop ...
3                           gop prays for ossoff lossoff
4      trevor noah says the scary truth about trump's...
...                                                  ...
11061  house conservatives claim democrats have faile...
11062  area man having one of his little bursts of en...
11063   there is nothing libertarian about conservatives
11064  mike pompeo startled after seeing 'beware of h...
11065        how pets can help prevent suicide #nspw2017

[11066 rows x 1 columns]

In [ ]:
import string
test['char_count'] = test['headline'].apply(len)
test['word_count'] = test['headline'].apply(lambda x: len(x.split()))
test['punctuation_count'] = test['headline'].apply(lambda x: len("".join(_ for _ in x if _ in string.punctuation))) 
test['title_word_count'] = test['headline'].apply(lambda x: len([wrd for wrd in x.split() if wrd.istitle()]))
test['upper_case_word_count'] = test['headline'].apply(lambda x: len([wrd for wrd in x.split() if wrd.isupper()]))

In [ ]:
test

,headline,char_count,word_count,punctuation_count,title_word_count,upper_case_word_count
0,area stand-up comedian questions the deal with...,65,9,2,0,0
1,dozens of glowing exit signs mercilessly taunt...,65,9,0,0,0
2,perfect response to heckler somewhere in prop ...,62,9,1,0,0
3,gop prays for ossoff lossoff,28,5,0,0,0
4,trevor noah says the scary truth about trump's...,65,11,1,0,0
...,...,...,...,...,...,...
11061,house conservatives claim democrats have faile...,65,8,0,0,0
11062,area man having one of his little bursts of en...,81,17,0,0,0
11063,there is nothing libertarian about conservatives,48,6,0,0,0
11064,mike pompeo startled after seeing 'beware of h...,87,14,2,0,0
11065,how pets can help prevent suicide #nspw2017,43,7,1,0,0

In [ ]:
headlinedata=test['headline']
test2=test.drop(['headline'],axis=1)

In [ ]:
headlinedata

0        area stand-up comedian questions the deal with...
1        dozens of glowing exit signs mercilessly taunt...
2        perfect response to heckler somewhere in prop ...
3                             gop prays for ossoff lossoff
4        trevor noah says the scary truth about trump's...
                               ...
11061    house conservatives claim democrats have faile...
11062    area man having one of his little bursts of en...
11063     there is nothing libertarian about conservatives
11064    mike pompeo startled after seeing 'beware of h...
11065          how pets can help prevent suicide #nspw2017
Name: headline, Length: 11066, dtype: object

In [ ]:
test2['prediction']=dt.predict(test2)

In [ ]:
test2

,char_count,word_count,punctuation_count,title_word_count,upper_case_word_count,prediction
0,65,9,2,0,0,0
1,65,9,0,0,0,0
2,62,9,1,0,0,0
3,28,5,0,0,0,1
4,65,11,1,0,0,0
...,...,...,...,...,...,...
11061,65,8,0,0,0,1
11062,81,17,0,0,0,1
11063,48,6,0,0,0,1
11064,87,14,2,0,0,0
11065,43,7,1,0,0,0

In [ ]:
test2.insert(loc=0, column = 'headline', value=headlinedata)

In [ ]:
test2

,headline,char_count,word_count,punctuation_count,title_word_count,upper_case_word_count,prediction
0,area stand-up comedian questions the deal with...,65,9,2,0,0,0
1,dozens of glowing exit signs mercilessly taunt...,65,9,0,0,0,0
2,perfect response to heckler somewhere in prop ...,62,9,1,0,0,0
3,gop prays for ossoff lossoff,28,5,0,0,0,1
4,trevor noah says the scary truth about trump's...,65,11,1,0,0,0
...,...,...,...,...,...,...,...
11061,house conservatives claim democrats have faile...,65,8,0,0,0,1
11062,area man having one of his little bursts of en...,81,17,0,0,0,1
11063,there is nothing libertarian about conservatives,48,6,0,0,0,1
11064,mike pompeo startled after seeing 'beware of h...,87,14,2,0,0,0
11065,how pets can help prevent suicide #nspw2017,43,7,1,0,0,0

In [ ]:
test3=test2.drop(['char_count','word_count','punctuation_count','title_word_count','upper_case_word_count'],axis=1)

In [ ]:
test3

                                                headline  prediction
0      area stand-up comedian questions the deal with...           0
1      dozens of glowing exit signs mercilessly taunt...           0
2      perfect response to heckler somewhere in prop ...           0
3                           gop prays for ossoff lossoff           1
4      trevor noah says the scary truth about trump's...           0
...                                                  ...         ...
11061  house conservatives claim democrats have faile...           1
11062  area man having one of his little bursts of en...           1
11063   there is nothing libertarian about conservatives           1
11064  mike pompeo startled after seeing 'beware of h...           0
11065        how pets can help prevent suicide #nspw2017           0

[11066 rows x 2 columns]

In [ ]:
test3 = pd.DataFrame(test3,columns=['prediction','headline'])

In [ ]:
test3.to_csv(f"Submission_rev.csv")